// Auto-generated ABI for AutonomousBountyDuel
// Copy-paste from Remix after compile if this drifts
export const DUEL_ABI = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  // ─── Read ───
  {
    inputs: [],
    name: "COMMIT_WINDOW",
    outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "REVEAL_WINDOW",
    outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nextTokenId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nextBountyId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nextDuelId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "getCharacter",
    outputs: [
      {
        components: [
          { internalType: "uint64", name: "hp", type: "uint64" },
          { internalType: "uint64", name: "attack", type: "uint64" },
          { internalType: "uint64", name: "defense", type: "uint64" },
          { internalType: "uint32", name: "wins", type: "uint32" },
          { internalType: "uint32", name: "losses", type: "uint32" },
          { internalType: "bool", name: "initialized", type: "bool" },
        ],
        internalType: "struct AutonomousBountyDuel.Character",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "bountyId", type: "uint256" }],
    name: "getBounty",
    outputs: [
      {
        components: [
          { internalType: "address", name: "poster", type: "address" },
          { internalType: "address", name: "target", type: "address" },
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "bool", name: "active", type: "bool" },
        ],
        internalType: "struct AutonomousBountyDuel.Bounty",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "duelId", type: "uint256" }],
    name: "getDuel",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "bountyId", type: "uint256" },
          { internalType: "address", name: "challenger", type: "address" },
          { internalType: "address", name: "target", type: "address" },
          { internalType: "uint256", name: "challengerTokenId", type: "uint256" },
          { internalType: "uint256", name: "targetTokenId", type: "uint256" },
          { internalType: "uint256", name: "challengerStake", type: "uint256" },
          { internalType: "uint256", name: "targetStake", type: "uint256" },
          { internalType: "bytes32", name: "challengerCommit", type: "bytes32" },
          { internalType: "bytes32", name: "targetCommit", type: "bytes32" },
          { internalType: "bool", name: "challengerRevealed", type: "bool" },
          { internalType: "bool", name: "targetRevealed", type: "bool" },
          { internalType: "uint8", name: "challengerMove", type: "uint8" },
          { internalType: "uint8", name: "targetMove", type: "uint8" },
          { internalType: "uint64", name: "commitDeadline", type: "uint64" },
          { internalType: "uint64", name: "revealDeadline", type: "uint64" },
          { internalType: "uint8", name: "state", type: "uint8" },
          { internalType: "address", name: "winner", type: "address" },
        ],
        internalType: "struct AutonomousBountyDuel.Duel",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "duelId", type: "uint256" },
      { internalType: "address", name: "player", type: "address" },
      { internalType: "uint8", name: "move", type: "uint8" },
      { internalType: "bytes32", name: "nonce", type: "bytes32" },
    ],
    name: "computeCommitment",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "ownerOf",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "balanceOf",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  // ─── Write ───
  {
    inputs: [],
    name: "mintCharacter",
    outputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "target", type: "address" }],
    name: "postBounty",
    outputs: [{ internalType: "uint256", name: "bountyId", type: "uint256" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "bountyId", type: "uint256" },
      { internalType: "uint256", name: "challengerTokenId", type: "uint256" },
      { internalType: "bytes32", name: "challengerCommit", type: "bytes32" },
    ],
    name: "createChallenge",
    outputs: [{ internalType: "uint256", name: "duelId", type: "uint256" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "duelId", type: "uint256" },
      { internalType: "uint256", name: "targetTokenId", type: "uint256" },
      { internalType: "bytes32", name: "targetCommit", type: "bytes32" },
    ],
    name: "acceptChallenge",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "duelId", type: "uint256" },
      { internalType: "uint8", name: "move", type: "uint8" },
      { internalType: "bytes32", name: "nonce", type: "bytes32" },
    ],
    name: "revealMove",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "duelId", type: "uint256" }],
    name: "resolveDuel",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  // ─── Events ───
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "owner", type: "address" },
      { indexed: true, internalType: "uint256", name: "tokenId", type: "uint256" },
      { indexed: false, internalType: "uint64", name: "hp", type: "uint64" },
      { indexed: false, internalType: "uint64", name: "attack", type: "uint64" },
      { indexed: false, internalType: "uint64", name: "defense", type: "uint64" },
    ],
    name: "CharacterMinted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "owner", type: "address" },
      { indexed: true, internalType: "uint256", name: "tokenId", type: "uint256" },
      { indexed: false, internalType: "uint64", name: "hp", type: "uint64" },
      { indexed: false, internalType: "uint64", name: "attack", type: "uint64" },
      { indexed: false, internalType: "uint64", name: "defense", type: "uint64" },
      { indexed: false, internalType: "uint32", name: "wins", type: "uint32" },
      { indexed: false, internalType: "uint32", name: "losses", type: "uint32" },
    ],
    name: "CharacterUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "bountyId", type: "uint256" },
      { indexed: true, internalType: "address", name: "poster", type: "address" },
      { indexed: true, internalType: "address", name: "target", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "BountyPosted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "duelId", type: "uint256" },
      { indexed: true, internalType: "uint256", name: "bountyId", type: "uint256" },
      { indexed: true, internalType: "address", name: "challenger", type: "address" },
      { indexed: false, internalType: "address", name: "target", type: "address" },
      { indexed: false, internalType: "uint256", name: "challengerStake", type: "uint256" },
      { indexed: false, internalType: "uint64", name: "commitDeadline", type: "uint64" },
    ],
    name: "DuelCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "duelId", type: "uint256" },
      { indexed: true, internalType: "address", name: "target", type: "address" },
      { indexed: false, internalType: "uint256", name: "targetStake", type: "uint256" },
      { indexed: false, internalType: "uint64", name: "revealDeadline", type: "uint64" },
    ],
    name: "DuelAccepted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "duelId", type: "uint256" },
      { indexed: true, internalType: "address", name: "player", type: "address" },
      { indexed: false, internalType: "bytes32", name: "commitment", type: "bytes32" },
    ],
    name: "MoveCommitted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "duelId", type: "uint256" },
      { indexed: true, internalType: "address", name: "player", type: "address" },
      { indexed: false, internalType: "uint8", name: "move", type: "uint8" },
    ],
    name: "MoveRevealed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "duelId", type: "uint256" },
      { indexed: true, internalType: "address", name: "winner", type: "address" },
      { indexed: false, internalType: "uint256", name: "payout", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "bountyAmount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "totalStakes", type: "uint256" },
    ],
    name: "DuelResolved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "duelId", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "returnedStake", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "bountyReturned", type: "uint256" },
    ],
    name: "DuelCanceled",
    type: "event",
  },
] as const;
